django_level_five/users_auth/auth_app/urls.py
from django.urls import path, include
from auth_app import views


app_name = 'auth_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

django_level_five/users_auth/users_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from auth_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('auth_app/', include('auth_app.urls')),
    path('logout/', views.user_logout, name = 'logout'),
    path('special/', views.special, name = 'special'),
]

django_level_five/users_auth/auth_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_image = models.ImageField(upload_to='profile_pics', blank=True)
    portfolio_site = models.URLField(blank=True)
    
    def __str__(self):
        return str(self.user.username)
        

django_level_five/users_auth/auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from auth_app.models import UserProfile


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'password', 'email')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('profile_image','portfolio_site')

django_level_five/users_auth/auth_app/views.py
from django.shortcuts import render
from auth_app.models import UserProfile
from django.contrib.auth.models import User
from django.forms import forms
from auth_app.forms import UserProfileForm, UserForm

from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.


def index(request):
    return render(request, 'auth_app/index.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def special(request):
    return HttpResponse(" YOU Have Got the Reward!!!")

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_image' in request.FILES:
                profile.profile_pic = request.FILES['profile_image']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'auth_app/registration.html', {'user_form': user_form,
                                                          'profile_form': profile_form,
                                                          'registered': registered})
    

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        
        user  = authenticate(username = username, password = password)
        
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
            else:
                return HttpResponse('User is not active')
            
        else:
            print("UserName: {} Password: {}".format(username, password))
            return HttpressResponse('Invalid login credentials')
    else:
        return render(request, 'auth_app/login.html', {})
            

django_level_five/users_auth/templates/auth_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'auth_app:index' %}">DJANGO</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_app:register' %}">Register</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'special' %}">Get New Login Bonus</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_app:user_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
</body>

</html>

django_level_five/users_auth/templates/auth_app/index.html
{% extends 'auth_app/base.html'%}

{% block body_block %}

    <div class="jumbotron">
        <h1>DJANGO LEVEL FIVE</h1>
    </div>

{% endblock %}

django_level_five/users_auth/templates/auth_app/login.html
{% extends 'auth_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
    <form action="{% url 'auth_app:user_login' %}" method="post">
        
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Username"/>
        <label for="password">password: </label>
        <input type="password" name="password" placeholder="Password"/>
        
        <input type="submit" value="Login"/>
    </form>

</div>

{% endblock %}

django_level_five/users_auth/templates/auth_app/registration.html
{% extends 'auth_app/base.html'%}

{% block body_block %}

    <div class="jumbotron">
        {% if registered %}
            <h1>Thanks You for registering!</h1>
        {% else %}
            <h1>Register Here!</h1>
            <form enctype="multipart/form" method="post">
                {% csrf_token %}
                {{user_form.as_p}}
                {{profile_form.as_p}}
                <input type="submit" class="btn btn-primary" value="Register"/>
            </form>
        {% endif %}
    </div>

{% endblock %}